import type { Locale } from './locales';

export type Feature = {
  id: string;
  icon: string;
  title: string;
  description: string;
};

const en: Feature[] = [
  { id: 'grammar',    icon: '✓',  title: 'Check Grammar',    description: 'Correct grammatical and spelling errors to perfect your text.' },
  { id: 'tone',       icon: '🎭', title: 'Tone Changer',     description: 'Alter the emotional undertone to suit your message — friendly, formal, sarcastic, and more.' },
  { id: 'ask',        icon: '🤖', title: 'Ask AI',           description: 'Get accurate answers to your questions in any language with AI.' },
  { id: 'translate',  icon: '🌐', title: 'Translate',        description: 'Broaden your reach with translations to over 55 languages.' },
  { id: 'paraphrase', icon: '↻',  title: 'Paraphrase',       description: "Express the same meaning with different words and maintain the text's essence." },
  { id: 'reply',      icon: '💬', title: 'Reply',            description: 'Engage in conversation with contextually relevant replies generated by AI.' },
  { id: 'continue',   icon: '➤',  title: 'Continue Text',    description: 'Seamlessly expand your narrative while preserving the original tone and language.' },
  { id: 'synonyms',   icon: '⇄',  title: 'Find Synonyms',    description: 'Enrich your vocabulary with linguistically diverse synonyms.' },
  { id: 'rewrite',    icon: '✨', title: 'Rewrite Post',     description: 'Make compelling social media posts that drive engagement.' },
  { id: 'autopaste',  icon: '📋', title: 'Auto Paste',       description: 'Effortlessly paste frequently used text for use in any context.' },
];

const de: Feature[] = [
  { id: 'grammar',    icon: '✓',  title: 'Grammatik prüfen',  description: 'Korrigiere grammatikalische und Rechtschreibfehler, um deinen Text zu perfektionieren.' },
  { id: 'tone',       icon: '🎭', title: 'Tonfall ändern',    description: 'Ändere den emotionalen Unterton — freundlich, formell, sarkastisch und mehr.' },
  { id: 'ask',        icon: '🤖', title: 'KI fragen',         description: 'Erhalte genaue Antworten auf deine Fragen in jeder Sprache mit KI.' },
  { id: 'translate',  icon: '🌐', title: 'Übersetzen',        description: 'Erweitere deine Reichweite mit Übersetzungen in über 55 Sprachen.' },
  { id: 'paraphrase', icon: '↻',  title: 'Umschreiben',       description: 'Drücke den gleichen Sinn mit anderen Worten aus und behalte die Essenz des Textes bei.' },
  { id: 'reply',      icon: '💬', title: 'Antworten',         description: 'Führe Gespräche mit kontextuell relevanten Antworten von KI.' },
  { id: 'continue',   icon: '➤',  title: 'Text fortsetzen',   description: 'Erweitere nahtlos deine Erzählung und behalte dabei den ursprünglichen Ton bei.' },
  { id: 'synonyms',   icon: '⇄',  title: 'Synonyme finden',   description: 'Bereichere deinen Wortschatz mit sprachlich vielfältigen Synonymen.' },
  { id: 'rewrite',    icon: '✨', title: 'Beitrag umschreiben', description: 'Erstelle überzeugende Social-Media-Beiträge.' },
  { id: 'autopaste',  icon: '📋', title: 'Auto-Einfügen',     description: 'Füge mühelos Text zur Verwendung in verschiedenen Kontexten ein.' },
];

const fr: Feature[] = [
  { id: 'grammar',    icon: '✓',  title: 'Vérification grammaticale', description: "Corrigez les erreurs grammaticales et d'orthographe pour perfectionner votre texte." },
  { id: 'tone',       icon: '🎭', title: 'Changeur de ton',  description: 'Modifiez le ton émotionnel — amical, formel, sarcastique et plus.' },
  { id: 'ask',        icon: '🤖', title: "Demandez à l'IA", description: "Obtenez des réponses précises à vos questions dans n'importe quelle langue avec l'IA." },
  { id: 'translate',  icon: '🌐', title: 'Traduire',          description: 'Élargissez votre portée avec des traductions dans plus de 55 langues.' },
  { id: 'paraphrase', icon: '↻',  title: 'Paraphraser',       description: "Exprimez la même idée avec des mots différents tout en conservant l'essence du texte." },
  { id: 'reply',      icon: '💬', title: 'Répondre',          description: 'Engagez la conversation avec des réponses contextuellement pertinentes générées par IA.' },
  { id: 'continue',   icon: '➤',  title: 'Continuer le texte', description: "Développez sans effort votre récit tout en préservant le ton et la langue d'origine." },
  { id: 'synonyms',   icon: '⇄',  title: 'Trouver des synonymes', description: 'Enrichissez votre vocabulaire avec des synonymes linguistiquement diversifiés.' },
  { id: 'rewrite',    icon: '✨', title: 'Réécrire le post',  description: 'Créez des posts de médias sociaux convaincants.' },
  { id: 'autopaste',  icon: '📋', title: 'Collage automatique', description: 'Collez sans effort du texte pour une utilisation dans divers contextes.' },
];

const es: Feature[] = [
  { id: 'grammar',    icon: '✓',  title: 'Revisar gramática',  description: 'Corrige errores gramaticales y ortográficos para perfeccionar tu texto.' },
  { id: 'tone',       icon: '🎭', title: 'Cambio de tono',     description: 'Altera el tono emocional — amigable, formal, sarcástico y más.' },
  { id: 'ask',        icon: '🤖', title: 'Preguntar a la IA',  description: 'Obtén respuestas precisas a tus preguntas en cualquier idioma con IA.' },
  { id: 'translate',  icon: '🌐', title: 'Traducir',           description: 'Amplía tu alcance con traducciones a más de 55 idiomas.' },
  { id: 'paraphrase', icon: '↻',  title: 'Parafrasear',        description: 'Expresa el mismo significado con diferentes palabras y mantén la esencia del texto.' },
  { id: 'reply',      icon: '💬', title: 'Responder',          description: 'Participa en conversaciones con respuestas contextualmente relevantes generadas por IA.' },
  { id: 'continue',   icon: '➤',  title: 'Continuar texto',    description: 'Expande tu narrativa sin problemas mientras preservas el tono y el lenguaje originales.' },
  { id: 'synonyms',   icon: '⇄',  title: 'Encontrar sinónimos', description: 'Enriquece tu vocabulario con sinónimos lingüísticamente diversos.' },
  { id: 'rewrite',    icon: '✨', title: 'Reescribir publicación', description: 'Crea publicaciones convincentes para redes sociales.' },
  { id: 'autopaste',  icon: '📋', title: 'Pegar automáticamente', description: 'Pega texto sin esfuerzo para usar en varios contextos.' },
];

const pt: Feature[] = [
  { id: 'grammar',    icon: '✓',  title: 'Verificar gramática', description: 'Corrige erros gramaticais e ortográficos para aperfeiçoar o teu texto.' },
  { id: 'tone',       icon: '🎭', title: 'Mudança de tom',     description: 'Altera o tom emocional — amigável, formal, sarcástico e mais.' },
  { id: 'ask',        icon: '🤖', title: 'Pergunta à IA',      description: 'Obtém respostas precisas para as tuas perguntas em qualquer idioma com IA.' },
  { id: 'translate',  icon: '🌐', title: 'Traduzir',           description: 'Amplia o teu alcance com traduções em mais de 55 idiomas.' },
  { id: 'paraphrase', icon: '↻',  title: 'Parafrasear',        description: 'Expressa o mesmo significado com palavras diferentes e mantém a essência do texto.' },
  { id: 'reply',      icon: '💬', title: 'Responder',          description: 'Participa em conversas com respostas contextualmente relevantes geradas por IA.' },
  { id: 'continue',   icon: '➤',  title: 'Continuar texto',    description: 'Expande a tua narrativa de forma contínua, preservando o tom e o idioma originais.' },
  { id: 'synonyms',   icon: '⇄',  title: 'Encontrar sinónimos', description: 'Enriquece o teu vocabulário com sinónimos linguisticamente diversos.' },
  { id: 'rewrite',    icon: '✨', title: 'Reescrever post',     description: 'Cria publicações convincentes para redes sociais.' },
  { id: 'autopaste',  icon: '📋', title: 'Colagem automática', description: 'Cola sem esforço texto para uso em vários contextos.' },
];

const ptBR: Feature[] = [
  { id: 'grammar',    icon: '✓',  title: 'Verificar gramática', description: 'Corrija erros gramaticais e ortográficos para aperfeiçoar seu texto.' },
  { id: 'tone',       icon: '🎭', title: 'Mudança de tom',     description: 'Altere o tom emocional — amigável, formal, sarcástico e mais.' },
  { id: 'ask',        icon: '🤖', title: 'Pergunte à IA',      description: 'Obtenha respostas precisas para suas perguntas em qualquer idioma com IA.' },
  { id: 'translate',  icon: '🌐', title: 'Traduzir',           description: 'Amplie seu alcance com traduções para mais de 55 idiomas.' },
  { id: 'paraphrase', icon: '↻',  title: 'Parafrasear',        description: 'Expresse o mesmo significado com palavras diferentes e mantenha a essência do texto.' },
  { id: 'reply',      icon: '💬', title: 'Responder',          description: 'Engaje-se em conversas com respostas contextualmente relevantes geradas por IA.' },
  { id: 'continue',   icon: '➤',  title: 'Continuar texto',    description: 'Expanda sua narrativa de forma contínua, preservando o tom e o idioma originais.' },
  { id: 'synonyms',   icon: '⇄',  title: 'Encontrar sinônimos', description: 'Enriqueça seu vocabulário com sinônimos linguisticamente diversos.' },
  { id: 'rewrite',    icon: '✨', title: 'Reescrever post',     description: 'Crie posts convincentes para redes sociais.' },
  { id: 'autopaste',  icon: '📋', title: 'Colagem automática', description: 'Cole texto sem esforço para uso em vários contextos.' },
];

export const FEATURES: Record<Locale, Feature[]> = {
  en, de, fr, es, pt, 'pt-br': ptBR,
};
