import type { Locale } from './locales';

export const LEGAL: Record<Locale, {
  privacyTitle: string;
  privacyIntro: string;
  privacyBodyMarkdown: string;
  termsTitle: string;
  termsIntro: string;
  termsBodyMarkdown: string;
  lastUpdated: string;
}> = {
  en: {
    privacyTitle: 'Privacy Policy',
    privacyIntro: "KeyAI is built with privacy as a default. This page explains exactly what data we send, when we send it, and what we don't.",
    privacyBodyMarkdown: `
## What we send to OpenAI

KeyAI only transmits text to OpenAI **when you tap an AI feature** (Grammar, Tone, Translate, Ask AI, Reply, Paraphrase, Continue, Synonyms, Rewrite). The text you selected is sent over HTTPS, the response is returned, and that's it.

We never silently capture what you type. We do not stream keystrokes. We do not store the text you submit on our servers — it goes directly to OpenAI for inference and is not retained by us.

## Apple's automatic protection

iOS automatically replaces any third-party keyboard with the system keyboard when you tap into:

- Password fields
- Credit card number fields
- Other secure inputs flagged by the app developer

This is an iOS guarantee, not something we can override. Your sensitive credentials are never seen by KeyAI.

## Full Access

iOS requires Full Access for any keyboard that uses the internet. KeyAI uses Full Access only to make HTTPS calls to OpenAI when you tap a feature. We don't log keystrokes, we don't read content from other apps, and we don't share data with third parties beyond what the AI features require.

## Analytics

We use Firebase Analytics to track aggregate, non-personally-identifying usage data: which features get tapped, app launches, subscription state, crash reports. Your subscription is handled by Apple's App Store; we never see your payment method.

## Subscriptions

Billing is handled entirely by Apple. We don't store credit card data. You can cancel any time in Settings → Apple ID → Subscriptions.

## Contact

Questions about privacy? Email **devxengine@gmail.com**.

For the most up-to-date legal version, see [enginesstudio.tech/privacy/keyai](https://enginesstudio.tech/privacy/keyai).
`,
    termsTitle: 'Terms of Use',
    termsIntro: 'These are the terms you agree to when you use KeyAI.',
    termsBodyMarkdown: `
## Subscription

KeyAI is offered as a weekly ($4.99) or yearly ($39.99) auto-renewing subscription via Apple's App Store. The 3-day free trial converts to a paid subscription unless cancelled at least 24 hours before the trial ends.

## Renewal

Subscriptions auto-renew until cancelled. To cancel, go to **Settings → Apple ID → Subscriptions** on your iPhone. Cancelling at least 24 hours before the renewal date stops the next billing cycle.

## Use of the AI

The AI features in KeyAI use OpenAI's language models. The output is generated by AI and may sometimes be inaccurate, inappropriate, or factually wrong. Treat AI output as a draft, not as authoritative information. We are not responsible for content generated by the AI.

## Acceptable use

Don't use KeyAI to harass, defame, or produce illegal content. Don't reverse-engineer the app or use it to violate someone's privacy.

## Disclaimer

KeyAI is provided "as is." We're not liable for damages arising from the use of the app beyond what's required by applicable consumer protection law.

## Contact

Questions about these terms? Email **devxengine@gmail.com**.
`,
    lastUpdated: 'Last updated: May 11, 2026',
  },
  de: {
    privacyTitle: 'Datenschutzerklärung',
    privacyIntro: 'KeyAI ist standardmäßig auf Privatsphäre ausgelegt. Diese Seite erklärt genau, welche Daten wir senden, wann wir sie senden und welche nicht.',
    privacyBodyMarkdown: `
## Was wir an OpenAI senden

KeyAI überträgt Text nur dann an OpenAI, **wenn du eine KI-Funktion antippst** (Grammatik, Tonfall, Übersetzen, KI fragen, Antworten, Umschreiben, Fortsetzen, Synonyme, Umschreiben). Der ausgewählte Text wird per HTTPS gesendet, die Antwort wird zurückgeschickt — das war's.

Wir erfassen niemals heimlich, was du tippst. Wir streamen keine Tastenanschläge. Wir speichern den übermittelten Text nicht auf unseren Servern.

## Apples automatischer Schutz

iOS ersetzt automatisch jede Drittanbieter-Tastatur durch die System-Tastatur, wenn du Folgendes antippst:

- Passwortfelder
- Kreditkartennummern-Felder
- Andere vom Entwickler als sensibel markierte Eingaben

Dies ist eine iOS-Garantie, die wir nicht außer Kraft setzen können.

## Vollzugriff

iOS erfordert Vollzugriff für jede Tastatur, die das Internet nutzt. KeyAI nutzt Vollzugriff ausschließlich für HTTPS-Aufrufe an OpenAI, wenn du eine Funktion antippst.

## Analytik

Wir nutzen Firebase Analytics für aggregierte, nicht personenbezogene Nutzungsdaten: welche Funktionen genutzt werden, App-Starts, Abonnementstatus, Crash-Berichte. Dein Abonnement wird vom App Store verwaltet; wir sehen niemals deine Zahlungsmethode.

## Abonnements

Die Abrechnung erfolgt vollständig über Apple. Wir speichern keine Kreditkartendaten.

## Kontakt

Fragen zum Datenschutz? E-Mail an **devxengine@gmail.com**.

Aktuelle Rechtsversion siehe [enginesstudio.tech/privacy/keyai](https://enginesstudio.tech/privacy/keyai).
`,
    termsTitle: 'Nutzungsbedingungen',
    termsIntro: 'Dies sind die Bedingungen, denen du bei der Nutzung von KeyAI zustimmst.',
    termsBodyMarkdown: `
## Abonnement

KeyAI wird als wöchentliches (4,99 €) oder jährliches (39,99 €) sich automatisch verlängerndes Abonnement über Apples App Store angeboten. Die 3-tägige kostenlose Testphase wandelt sich in ein kostenpflichtiges Abonnement um, sofern sie nicht mindestens 24 Stunden vor Ende der Testphase gekündigt wird.

## Verlängerung

Abonnements verlängern sich automatisch, bis sie gekündigt werden. Gehe zu **Einstellungen → Apple-ID → Abonnements** auf deinem iPhone, um zu kündigen.

## Nutzung der KI

Die KI-Funktionen nutzen OpenAIs Sprachmodelle. Die Ausgabe kann manchmal ungenau, unangemessen oder sachlich falsch sein. Behandle KI-Ausgaben als Entwurf, nicht als verbindliche Information.

## Akzeptable Nutzung

Nutze KeyAI nicht für Belästigung, Diffamierung oder illegale Inhalte. Reverse-Engineere die App nicht.

## Haftungsausschluss

KeyAI wird "wie besehen" bereitgestellt. Wir haften nicht für Schäden über das hinaus, was geltendes Verbraucherrecht erfordert.

## Kontakt

Fragen zu diesen Bedingungen? E-Mail an **devxengine@gmail.com**.
`,
    lastUpdated: 'Zuletzt aktualisiert: 11. Mai 2026',
  },
  fr: {
    privacyTitle: 'Politique de confidentialité',
    privacyIntro: 'KeyAI est conçu avec la confidentialité par défaut. Cette page explique exactement quelles données nous envoyons, quand nous les envoyons et lesquelles nous ne touchons pas.',
    privacyBodyMarkdown: `
## Ce que nous envoyons à OpenAI

KeyAI transmet du texte à OpenAI **uniquement lorsque vous tapotez une fonction IA** (Grammaire, Ton, Traduction, Demander à l'IA, Répondre, Paraphraser, Continuer, Synonymes, Réécrire). Le texte sélectionné est envoyé en HTTPS, la réponse est retournée, c'est tout.

Nous ne capturons jamais silencieusement ce que vous tapez. Nous ne diffusons pas de frappes au clavier. Nous ne stockons pas le texte soumis sur nos serveurs.

## Protection automatique d'Apple

iOS remplace automatiquement tout clavier tiers par le clavier système lorsque vous tapotez :

- Les champs de mot de passe
- Les champs de numéro de carte de crédit
- D'autres saisies sensibles signalées par le développeur de l'app

C'est une garantie iOS que nous ne pouvons pas outrepasser.

## Accès complet

iOS exige l'accès complet pour tout clavier utilisant Internet. KeyAI utilise l'accès complet uniquement pour des appels HTTPS à OpenAI lorsque vous tapotez une fonction.

## Analytique

Nous utilisons Firebase Analytics pour des données d'usage agrégées et non personnelles : fonctions tapotées, lancements d'app, état d'abonnement, rapports de crash. Votre abonnement est géré par l'App Store ; nous ne voyons jamais votre moyen de paiement.

## Abonnements

La facturation est entièrement gérée par Apple. Nous ne stockons aucune donnée de carte de crédit.

## Contact

Des questions sur la confidentialité ? Envoyez un email à **devxengine@gmail.com**.

Version légale à jour : [enginesstudio.tech/privacy/keyai](https://enginesstudio.tech/privacy/keyai).
`,
    termsTitle: "Conditions d'utilisation",
    termsIntro: "Voici les conditions que vous acceptez en utilisant KeyAI.",
    termsBodyMarkdown: `
## Abonnement

KeyAI est offert en abonnement hebdomadaire (4,99 €) ou annuel (39,99 €) à renouvellement automatique via l'App Store d'Apple. L'essai gratuit de 3 jours se transforme en abonnement payant sauf annulation au moins 24 heures avant la fin de l'essai.

## Renouvellement

Les abonnements se renouvellent automatiquement jusqu'à annulation. Allez dans **Réglages → Apple ID → Abonnements** sur votre iPhone pour annuler.

## Utilisation de l'IA

Les fonctions IA utilisent les modèles de langage d'OpenAI. La sortie peut parfois être inexacte, inappropriée ou factuellement erronée. Traitez la sortie IA comme un brouillon, pas comme une information autoritative.

## Utilisation acceptable

N'utilisez pas KeyAI pour harceler, diffamer ou produire du contenu illégal. Ne procédez pas à de l'ingénierie inverse.

## Avertissement

KeyAI est fourni "en l'état". Nous ne sommes pas responsables des dommages au-delà de ce qui est requis par le droit de la consommation applicable.

## Contact

Des questions sur ces conditions ? Envoyez un email à **devxengine@gmail.com**.
`,
    lastUpdated: 'Dernière mise à jour : 11 mai 2026',
  },
  es: {
    privacyTitle: 'Política de privacidad',
    privacyIntro: 'KeyAI está construido con privacidad por defecto. Esta página explica exactamente qué datos enviamos, cuándo los enviamos y qué no.',
    privacyBodyMarkdown: `
## Lo que enviamos a OpenAI

KeyAI solo transmite texto a OpenAI **cuando tocas una función IA** (Gramática, Tono, Traducir, Preguntar a la IA, Responder, Parafrasear, Continuar, Sinónimos, Reescribir). El texto seleccionado se envía por HTTPS, la respuesta se devuelve, y eso es todo.

Nunca capturamos silenciosamente lo que escribes. No transmitimos pulsaciones de teclas. No almacenamos el texto enviado en nuestros servidores.

## Protección automática de Apple

iOS reemplaza automáticamente cualquier teclado de terceros con el teclado del sistema cuando tocas:

- Campos de contraseña
- Campos de número de tarjeta de crédito
- Otras entradas sensibles marcadas por el desarrollador de la app

Es una garantía de iOS que no podemos anular.

## Acceso completo

iOS requiere acceso completo para cualquier teclado que use Internet. KeyAI usa el acceso completo únicamente para llamadas HTTPS a OpenAI cuando tocas una función.

## Analítica

Usamos Firebase Analytics para datos de uso agregados y no personales: funciones tocadas, lanzamientos de app, estado de suscripción, informes de fallos. Tu suscripción la gestiona App Store; nunca vemos tu método de pago.

## Suscripciones

La facturación la gestiona Apple por completo. No almacenamos datos de tarjetas.

## Contacto

¿Preguntas sobre privacidad? Envía un email a **devxengine@gmail.com**.

Versión legal actualizada: [enginesstudio.tech/privacy/keyai](https://enginesstudio.tech/privacy/keyai).
`,
    termsTitle: 'Términos de uso',
    termsIntro: 'Estos son los términos que aceptas al usar KeyAI.',
    termsBodyMarkdown: `
## Suscripción

KeyAI se ofrece como suscripción semanal (4,99 €) o anual (39,99 €) con renovación automática a través del App Store de Apple. La prueba gratuita de 3 días se convierte en suscripción de pago a menos que se cancele al menos 24 horas antes de que termine la prueba.

## Renovación

Las suscripciones se renuevan automáticamente hasta su cancelación. Ve a **Ajustes → Apple ID → Suscripciones** en tu iPhone para cancelar.

## Uso de la IA

Las funciones IA usan los modelos de lenguaje de OpenAI. La salida puede ser a veces inexacta, inapropiada o factualmente incorrecta. Trata la salida IA como borrador, no como información autoritativa.

## Uso aceptable

No uses KeyAI para acosar, difamar o producir contenido ilegal. No realices ingeniería inversa.

## Descargo

KeyAI se proporciona "tal cual". No somos responsables de daños más allá de lo que requiera la legislación aplicable de protección al consumidor.

## Contacto

¿Preguntas sobre estos términos? Envía un email a **devxengine@gmail.com**.
`,
    lastUpdated: 'Última actualización: 11 de mayo de 2026',
  },
  pt: {
    privacyTitle: 'Política de Privacidade',
    privacyIntro: 'O KeyAI é construído com privacidade por defeito. Esta página explica exatamente que dados enviamos, quando os enviamos e quais não tocamos.',
    privacyBodyMarkdown: `
## O que enviamos para a OpenAI

O KeyAI só transmite texto para a OpenAI **quando tocas numa funcionalidade IA** (Gramática, Tom, Tradução, Perguntar à IA, Responder, Parafrasear, Continuar, Sinónimos, Reescrever). O texto selecionado é enviado por HTTPS, a resposta é devolvida, e é tudo.

Nunca capturamos silenciosamente o que escreves. Não transmitimos teclas. Não armazenamos o texto submetido nos nossos servidores.

## Proteção automática da Apple

O iOS substitui automaticamente qualquer teclado de terceiros pelo teclado do sistema quando tocas:

- Campos de palavra-passe
- Campos de número de cartão de crédito
- Outras entradas sensíveis sinalizadas pelo programador da app

É uma garantia do iOS que não podemos anular.

## Acesso Total

O iOS exige Acesso Total para qualquer teclado que use a internet. O KeyAI usa Acesso Total apenas para chamadas HTTPS à OpenAI quando tocas numa funcionalidade.

## Analítica

Usamos Firebase Analytics para dados de uso agregados e não pessoais. A tua subscrição é gerida pela App Store; nunca vemos o teu método de pagamento.

## Subscrições

A faturação é gerida totalmente pela Apple. Não armazenamos dados de cartão.

## Contacto

Dúvidas sobre privacidade? Envia email para **devxengine@gmail.com**.

Versão legal mais atualizada: [enginesstudio.tech/privacy/keyai](https://enginesstudio.tech/privacy/keyai).
`,
    termsTitle: 'Termos de Utilização',
    termsIntro: 'Estes são os termos que aceitas ao utilizar o KeyAI.',
    termsBodyMarkdown: `
## Subscrição

O KeyAI é oferecido como subscrição semanal (4,99 €) ou anual (39,99 €) com renovação automática via App Store da Apple. O período gratuito de 3 dias converte-se em subscrição paga a não ser que seja cancelado pelo menos 24 horas antes do fim do período gratuito.

## Renovação

As subscrições renovam-se automaticamente até serem canceladas. Vai a **Ajustes → Apple ID → Subscrições** no teu iPhone para cancelar.

## Utilização da IA

As funcionalidades IA usam modelos de linguagem da OpenAI. A saída pode por vezes ser imprecisa, inadequada ou factualmente incorreta. Trata a saída da IA como rascunho.

## Uso aceitável

Não uses o KeyAI para assediar, difamar ou produzir conteúdo ilegal. Não faças engenharia reversa.

## Aviso

O KeyAI é fornecido "tal como está". Não somos responsáveis por danos além do exigido pela legislação aplicável de proteção do consumidor.

## Contacto

Dúvidas sobre estes termos? Envia email para **devxengine@gmail.com**.
`,
    lastUpdated: 'Última atualização: 11 de maio de 2026',
  },
  'pt-br': {
    privacyTitle: 'Política de Privacidade',
    privacyIntro: 'O KeyAI é construído com privacidade por padrão. Esta página explica exatamente quais dados enviamos, quando enviamos e quais não.',
    privacyBodyMarkdown: `
## O que enviamos para a OpenAI

O KeyAI só transmite texto à OpenAI **quando você toca em um recurso IA** (Gramática, Tom, Tradução, Perguntar à IA, Responder, Parafrasear, Continuar, Sinônimos, Reescrever). O texto selecionado é enviado via HTTPS, a resposta é retornada, e é só isso.

Nunca capturamos silenciosamente o que você digita. Não transmitimos teclas. Não armazenamos o texto enviado em nossos servidores.

## Proteção automática da Apple

O iOS substitui automaticamente qualquer teclado de terceiros pelo teclado do sistema quando você toca em:

- Campos de senha
- Campos de número de cartão de crédito
- Outras entradas sensíveis sinalizadas pelo desenvolvedor do app

É uma garantia do iOS que não podemos anular.

## Acesso Total

O iOS exige Acesso Total para qualquer teclado que use a internet. O KeyAI usa Acesso Total apenas para chamadas HTTPS à OpenAI quando você toca em um recurso.

## Analytics

Usamos Firebase Analytics para dados de uso agregados e não pessoais. Sua assinatura é gerenciada pela App Store; nunca vemos seu método de pagamento.

## Assinaturas

A cobrança é gerenciada totalmente pela Apple. Não armazenamos dados de cartão.

## Contato

Dúvidas sobre privacidade? Envie email para **devxengine@gmail.com**.

Versão legal mais atualizada: [enginesstudio.tech/privacy/keyai](https://enginesstudio.tech/privacy/keyai).
`,
    termsTitle: 'Termos de Uso',
    termsIntro: 'Estes são os termos que você aceita ao usar o KeyAI.',
    termsBodyMarkdown: `
## Assinatura

O KeyAI é oferecido como assinatura semanal (R$ 24,90) ou anual (R$ 199,90) com renovação automática via App Store da Apple. O teste grátis de 3 dias se converte em assinatura paga, a menos que seja cancelado pelo menos 24 horas antes do fim do teste.

## Renovação

As assinaturas se renovam automaticamente até serem canceladas. Vá em **Ajustes → Apple ID → Assinaturas** no seu iPhone para cancelar.

## Uso da IA

Os recursos IA usam os modelos de linguagem da OpenAI. A saída pode às vezes ser imprecisa, inadequada ou factualmente incorreta. Trate a saída da IA como rascunho.

## Uso aceitável

Não use o KeyAI para assediar, difamar ou produzir conteúdo ilegal. Não faça engenharia reversa.

## Aviso

O KeyAI é fornecido "como está". Não somos responsáveis por danos além do exigido pela legislação aplicável de proteção ao consumidor.

## Contato

Dúvidas sobre estes termos? Envie email para **devxengine@gmail.com**.
`,
    lastUpdated: 'Última atualização: 11 de maio de 2026',
  },
};

// Tiny markdown-ish renderer for legal pages (h2 + paragraphs + lists + links + bold)
export function renderLegalMarkdown(md: string): string {
  const lines = md.trim().split('\n');
  const out: string[] = [];
  let listOpen = false;

  const inline = (s: string) =>
    s
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith('## ')) {
      if (listOpen) { out.push('</ul>'); listOpen = false; }
      out.push(`<h2>${inline(line.slice(3))}</h2>`);
    } else if (line.startsWith('- ')) {
      if (!listOpen) { out.push('<ul>'); listOpen = true; }
      out.push(`<li>${inline(line.slice(2))}</li>`);
    } else if (line === '') {
      if (listOpen) { out.push('</ul>'); listOpen = false; }
    } else {
      if (listOpen) { out.push('</ul>'); listOpen = false; }
      out.push(`<p>${inline(line)}</p>`);
    }
  }
  if (listOpen) out.push('</ul>');
  return out.join('\n');
}
